[build]
  publish = "AramaSite/public"
  command = "cd AramaSite && hugo --gc --minify --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.134.2"
  HUGO_ENV = "production"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://arama-a.netlify.app/"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"