[en]
title = "My blog"
weight = 1
LanguageName = "EN"
contentDir = "content/english"

[ru]
title = "Блог"
weight = 12
LanguageName = "RU"
contentDir = "content/russian"
contentDir = "content/russian"
#dateFormat = "02.01.2006"  # Формат даты: день.месяц.год
#timeFormat = "15:04"       # Формат времени: часы:минуты
