  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Блог"
  weight = 200
  identifier = "posts"
  url = "/post/"

#  [[main]]
#  name = "Portfolio"
#  weight = 300
#  identifier = "portfolio"
#  url = "/portfolio/"

  [[main]]
  name = "Обо мне"
  weight = 400
  identifier = "about"
  url = "/about/"

#  [[main]]
#  name = "Accomplishments"
#  weight = 500
#  identifier = "accomplishments"

  [[main]]
  name = "Гонки"
  weight = 510
  identifier = "awards"
  url = "/awards/"
#  parent = "accomplishments"  

  [[main]]
  name = "Сертификаты"
  weight = 520
  identifier = "certifications"
  url = "/certifications/"
 # parent = "accomplishments"

  [[main]]
  name = "Контакты"
  weight = 600
  identifier = "contact"
  url = "/contact/"

  #[[footer]]
  #name = "imprint"
  #weight = 1
  #identifier = "imprint"
  #url = "/imprint/"