name: Deploy Hugo Yandexw rclone

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Важно для тем Hugo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Install rclone
        run: |
          curl -O https://downloads.rclone.org/rclone-current-linux-amd64.deb
          sudo dpkg -i rclone-current-linux-amd64.deb
          rclone version

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "[yandex]
          type = s3
          provider = Other
          env_auth = false
          access_key_id = ${{ secrets.S3_ACCESS_KEY }}
          secret_access_key = ${{ secrets.S3_SECRET_KEY }}
          endpoint = ${{ secrets.S3_BUCKET }}
          region = ru-central1
          acl = public-read" > ~/.config/rclone/rclone.conf

      - name: Deploy to Yandex Cloud
        run: |
          rclone sync ./public yandex:${{ secrets.S3_BUCKET }} \
            --progress \
            --s3-acl=public-read \
            --s3-no-head-object  # Ускоряет загрузку
          
          # Принудительно обновляем index.html с правильными заголовками
          rclone copy ./public/index.html yandex:${{ secrets.S3_BUCKET }} \
            --header-upload "Cache-Control:no-cache, max-age=0" \
            --header-upload "Content-Type:text/html"
